import s1Logo from './Images/Borneo.png';
import s2Logo from './Images/Australia.png';
import s3Logo from './Images/Africa.png';
import s4Logo from './Images/Marquesas.png';
import s5Logo from './Images/Thailand.png';
import s6Logo from './Images/Amazon.png';
import s7Logo from './Images/Pearl Islands.png';
import s8Logo from './Images/All-Stars.png';
import s9Logo from './Images/Vanuatu.png';
import s10Logo from './Images/Palau.png';
import s11Logo from './Images/Guatemala.png';
import s12Logo from './Images/Panama.png';
import s13Logo from './Images/Cook Islands.png';
import s14Logo from './Images/Fiji.png';
import s15Logo from './Images/China.png';
import s16Logo from './Images/Micronesia.png';
import s17Logo from './Images/Gabon.png';
import s18Logo from './Images/Tocantins.png';
import s19Logo from './Images/Samoa.png';
import s20Logo from './Images/HeroesVillians.png';
import s21Logo from './Images/Nicaragua.png';
import s22Logo from './Images/Redemption Island.png';
import s23Logo from './Images/South Pacific.png';
import s24Logo from './Images/One World.png';
import s25Logo from './Images/Philippines.png';
import s26Logo from './Images/Caramoan.png';
import s27Logo from './Images/Blood vs Water.png';
import s28Logo from './Images/Cagayan.png';
import s29Logo from './Images/San Juan del Sur.png';
import s30Logo from './Images/Worlds Apart.png';
import s31Logo from './Images/Cambodia.png';
import s32Logo from './Images/Kaoh Rong.png';
import s33Logo from './Images/MvG.png';
import s34Logo from './Images/Game Changers.png';
import s35Logo from './Images/HHH.png';
import s36Logo from './Images/Ghost Island.png';
import s37Logo from './Images/David vs Goliath.png';
import s38Logo from './Images/Edge of Extinction.png';
import s39Logo from './Images/Island of the Idols.png';
import s40Logo from './Images/Winners at War.png';
import s41Logo from './Images/41.png';

let seasonData = new Map();
seasonData.set(1, {
    seasonName: "Borneo",
    seasonWinner: "Richard Hatch",
    showWinner: false,
    seasonLogo: s1Logo,
    seasonColor: "#3ba545",
    castType: "newbie", // newbie, returnee, or mixed
    numTribes: "two", // # tribes to start game ("two", "three", "four")
    finalTribal: 2, // # of players in final tribal (2, 3)
    secondChance: "none", // second chance rules for voted out players ("none", "redemption", "outcast", "edge")
    tier: 1,
    seasonCast: ["BB Anderson",
                "Colleen Haskel",
                "Dirk Been",
                "Gervase Peterson",
                "Greg Buis",
                "Gretchen Cordy",
                "Jenna Lewis",
                "Joel Klug",
                "Kelly Wiglesworth",
                "Ramona Gray",
                "Richard Hatch",
                "Rudy Boesch",
                "Sean Kenniff",
                "Sonja Christopher",
                "Stacey Stillman",
                "Susan Hawk"]
});

seasonData.set(2, {
    seasonName: "Australian Outback",
    seasonWinner: "Tina Wesson",
    showWinner: false,
    seasonLogo: s2Logo,
    seasonColor: "#6f2229",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 2,
    secondChance: "none",
    tier: 4,
    seasonCast: ["Alicia Calaway",
                "Amber Mariano (Brkich)",
                "Colby Donaldson",
                "Debb Eaton",
                "Elisabeth Filarski",
                "Jeff Varner",
                "Jerri Manthey",
                "Keith Famie",
                "Kel Gleason",
                "Kimmi Kappenberg",
                "Maralyn Hershey",
                "Michael Skupin",
                "Mitchell Olson",
                "Nick Brown",
                "Rodger Bingham",
                "Tina Wesson"]
});

seasonData.set(3, {
    seasonName: "Africa",
    seasonWinner: "Ethan Zohn",
    showWinner: false,
    seasonLogo: s3Logo,
    seasonColor: "#ed6327",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 2,
    secondChance: "none",
    tier: 2,
    seasonCast: ["Brandon Quinton",
                "Carl Bilancione",
                "Clarence Black",
                "Diane Ogden",
                "Ethan Zohn",
                "Frank Garrison",
                "Jessie Camacho",
                "Kelly Goldsmith",
                "Kim Johnson",
                "Kim Powers",
                "Lex van den Berghe",
                "Linda Spencer",
                "Lindsey Richter",
                "Silas Gaither",
                "Teresa Cooper",
                "Tom Buchanan"]
});

seasonData.set(4, {
    seasonName: "Marquesas",
    seasonWinner: "Vecepia Towery",
    showWinner: false,
    seasonLogo: s4Logo,
    seasonColor: "#74cae1",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 2,
    secondChance: "none",
    tier: 4,
    seasonCast: ["Gabriel Cade",
                "Gina Crews",
                "Hunter Ellis",
                "John Carroll",
                "Kathy Vavrick-O'Brien",
                "Neleh Dennis",
                "Paschal English",
                "Patricia Jackson",
                "Peter Harkey",
                "Rob Mariano",
                "Robert DeCanio",
                "Sarah Jones",
                "Sean Rector",
                "Tammy Leitner",
                "Vecepia Towery",
                "Zoe Zanidakis"]
});

seasonData.set(5, {
    seasonName: "Thailand",
    seasonWinner: "Brian Heidik",
    showWinner: false,
    seasonLogo: s5Logo,
    seasonColor: "#4d1f5d",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 2,
    secondChance: "none",
    tier: 4,
    seasonCast: ["Brian Heidik",
                "Clay Jordan",
                "Erin Collins",
                "Ghandia Johnson",
                "Helen Glover",
                "Jake Billingsley",
                "Jan Gentry",
                "Jed Hildebrand",
                "John Raymond",
                "Ken Stafford",
                "Penny Ramsey",
                "Robb Zbacnik",
                "Shii Ann Huang",
                "Stephanie Dill",
                "Tanya Vance",
                "Ted Rogers Jr"]
});

seasonData.set(6, {
    seasonName: "Amazon",
    seasonWinner: "Jenna Morasca",
    showWinner: false,
    seasonLogo: s6Logo,
    seasonColor: "#015f11",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 2,
    secondChance: "none",
    tier: 1,
    seasonCast: ["Alex Bell",
                "Butch Lockley",
                "Christy Smith",
                "Daniel Lue",
                "Dave Johnson",
                "Deena Bennett",
                "Heidi Strobel",
                "Janet Koth",
                "Jeanne Hebert",
                "Jenna Morasca",
                "JoAnna Ward",
                "Matthew von Ertfelda",
                "Rob Cesternino",
                "Roger Sexton",
                "Ryan Aiken",
                "Shawna Mitchell"]
});

seasonData.set(7, {
    seasonName: "Pearl Islands",
    showWinner: false,
    seasonWinner: "Sandra Diaz-Twine",
    seasonLogo: s7Logo,
    seasonColor: "#003f9c",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 2,
    secondChance: "outcast",
    tier: 1,
    seasonCast: ["Andrew Savage",
                "Burton Roberts",
                "Christa Hastie",
                "Darrah Johnson",
                "Jon Dalton",
                "Lillian Morris",
                "Michelle Tesauro",
                "Nicole Delma",
                "Osten Taylor",
                "Rupert Boneham",
                "Ryan Opray",
                "Ryan Shoulders",
                "Sandra Diaz-Twine",
                "Shawn Cohen",
                "Tijuana Bradley",
                "Trish Dunn"]
});

seasonData.set(8, {
    seasonName: "All-Stars",
    seasonWinner: "Amber Brkich",
    showWinner: false,
    seasonLogo: s8Logo,
    seasonColor: "#f8931c",
    castType: "returnee",
    numTribes: "three",
    finalTribal: 2,
    secondChance: "none",
    tier: 3,
    seasonCast: ["Alicia Calaway",
                "Amber Mariano (Brkich)",
                "Colby Donaldson",
                "Ethan Zohn",
                "Jenna Lewis",
                "Jenna Morasca",
                "Jerri Manthey",
                "Kathy Vavrick-O'Brien",
                "Lex van den Berghe",
                "Richard Hatch",
                "Rob Cesternino",
                "Rob Mariano",
                "Rudy Boesch",
                "Rupert Boneham",
                "Shii Ann Huang",
                "Susan Hawk",
                "Tina Wesson",
                "Tom Buchanan"]
});

seasonData.set(9, {
    seasonName: "Vanuatu",
    seasonWinner: "Chris Daugherty",
    showWinner: false,
    seasonLogo: s9Logo,
    seasonColor: "#f2e00f",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 2,
    secondChance: "none",
    tier: 3,
    seasonCast: ["Ami Cusack",
                "Brady Finta",
                "Brook Geraghty",
                "Chad Crittenden",
                "Chris Daugherty",
                "Dolly Neely",
                "Eliza Orlins",
                "John Kenney",
                "John Palyok",
                "Julie Berry",
                "Lea Masters",
                "Leann Slaby",
                "Lisa Keiffer",
                "Mia Galeotalanza",
                "Rory Freeman",
                "Scout Cloud Lee",
                "Travis Sampson",
                "Twila Tanner"]
});

seasonData.set(10, {
    seasonName: "Palau",
    seasonWinner: "Tom Westman",
    showWinner: false,
    seasonLogo: s10Logo,
    seasonColor: "#53741b",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 2,
    secondChance: "none",
    tier: 2,
    seasonCast: ['Angie Jakusz',
                'Ashlee Ashby',
                'Bobby Jon Drinkard',
                'Caryn Groedel',
                'Coby Archa',
                'Gregg Carey',
                'Ian Rosenberger',
                'Ibrehem Rahman',
                'James Miller',
                'Janu Tornell',
                'Jeff Wilson',
                'Jenn Lyon',
                'Jolanda Jones',
                'Jonathan Libby',
                'Katie Gallagher',
                'Kim Mullen',
                'Stephenie LaGrossa',
                'Tom Westman',
                'Wanda Shirk',
                'Willard Smith']
});

seasonData.set(11, {
    seasonName: "Guatemala",
    seasonWinner: "Danni Boatwright",
    showWinner: false,
    seasonLogo: s11Logo,
    seasonColor: "#0ea7a4",
    castType: "mixed",
    numTribes: "two",
    finalTribal: 2,
    secondChance: "none",
    tier: 3,
    seasonCast: ["Amy O'Hara",
                'Blake Towsley',
                'Bobby Jon Drinkard',
                'Brandon Bellinger',
                'Brian Corridan',
                'Brianna Varela',
                'Brooke Struck',
                'Cindy Hall',
                'Danni Boatwright',
                'Gary Hogeboom',
                'Jamie Newton',
                'Jim Lynch',
                'Judd Sergeant',
                'Lydia Morales',
                'Margaret Bobonich',
                'Morgan McDevitt',
                'Rafe Judkins',
                'Stephenie LaGrossa']
});

seasonData.set(12, {
    seasonName: "Panama",
    seasonWinner: "Aras Baskauskas",
    showWinner: false,
    seasonLogo: s12Logo,
    seasonColor: "#e22126",
    castType: "newbie",
    numTribes: "four",
    finalTribal: 2,
    secondChance: "none",
    tier: 3,
    seasonCast: ['Aras Baskauskas',
                'Austin Carty',
                'Bobby Mason',
                'Bruce Kanegai',
                'Cirie Fields',
                'Courtney Marit',
                'Dan Barry',
                'Danielle DiLorenzo',
                'Melinda Hyder',
                'Misty Giles',
                'Nick Stanbury',
                'Ruth Marie Milliman',
                'Sally Schumann',
                'Shane Powers',
                'Terry Deitz',
                'Tina Scheer']
});

seasonData.set(13, {
    seasonName: "Cook Islands",
    showWinner: false,
    seasonWinner: "Yul Kwon",
    seasonLogo: s13Logo,
    seasonColor: "#8d232a",
    castType: "newbie",
    numTribes: "four",
    finalTribal: 3,
    secondChance: "none",
    tier: 2,
    seasonCast: ['Adam Gentry',
                'Becky Lee',
                'Billy Garcia',
                'Brad Virata',
                'Candice Cody (Woodcock)',
                'Cao Boi Bui',
                'Cecilia Mansilla',
                'Cristina Coria',
                'J.P. Calderon',
                'Jenny Guzon-Bae',
                'Jessica Smith',
                'Jonathan Penner',
                'Nate Gonzalez',
                'Ozzy Lusth',
                'Parvati Shallow',
                'Rebecca Borman',
                'Sekou Bunch',
                'Stephannie Favor',
                'Sundra Oakley',
                'Yul Kwon']
});

seasonData.set(14, {
    seasonName: "Fiji",
    seasonWinner: "Earl Cole",
    showWinner: false,
    seasonLogo: s14Logo,
    seasonColor: "#be7347",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "none",
    tier: 4,
    seasonCast: ['Alex Angarita',
                'Anthony Robinson',
                'Boo Bernis',
                'Cassandra Franklin',
                'Dreamz Herd',
                'Earl Cole',
                'Edgardo Rivera',
                'Erica Durousseau',
                'Gary Stritesky',
                'Jessica deBen',
                'Liliana Gomez',
                'Lisi Linares',
                'Michelle Yi',
                'Mookie Lee',
                'Rita Verreos',
                'Rocky Reid',
                'Stacy Kimball',
                'Sylvia Kwan',
                'Yau-Man Chan']
});

seasonData.set(15, {
    seasonName: "China",
    seasonWinner: "Todd Herzog",
    showWinner: false,
    seasonLogo: s15Logo,
    seasonColor: "#8c8c8c",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "none",
    tier: 2,
    seasonCast: ['Aaron Reisberger',
                'Amanda Kimmel',
                'Ashley Massaro',
                'Chicken Morris',
                'Courtney Yates',
                'Dave Cruser',
                'Denise Martin',
                'Erik Huffman',
                'Frosti Zernow',
                'Jaime Dugan',
                'James Clement',
                'Jean-Robert Bellande',
                'Leslie Nease',
                'Peih-Gee Law',
                'Sherea Lloyd',
                'Todd Herzog']
});

seasonData.set(16, {
    seasonName: "Micronesia",
    seasonWinner: "Parvati Shallow",
    showWinner: false,
    seasonLogo: s16Logo,
    seasonColor: "#febf10",
    castType: "mixed",
    numTribes: "two",
    finalTribal: 2,
    secondChance: "none",
    tier: 2,
    seasonCast: ['Alexis Jones',
                'Amanda Kimmel',
                'Ami Cusack',
                'Chet Welch',
                'Cirie Fields',
                'Eliza Orlins',
                'Erik Reichenbach',
                'James Clement',
                'Jason Siska',
                'Joel Anderson',
                'Jon Dalton',
                'Jonathan Penner',
                'Kathy Sleckman',
                'Mary Sartain',
                'Mikey Bortone',
                'Natalie Bolton',
                'Ozzy Lusth',
                'Parvati Shallow',
                'Tracy Hughes-Wolf',
                'Yau-Man Chan']
});

seasonData.set(17, {
    seasonName: "Gabon",
    seasonWinner: "Bob Crowley",
    showWinner: false,
    seasonLogo: s17Logo,
    seasonColor: "#59a856",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "none",
    tier: 4,
    seasonCast: ['Ace Gordon',
                'Bob Crowley',
                'Charlie Herschel',
                'Corinne Kaplan',
                'Crystal Cox',
                'Dan Kay',
                'GC Brown',
                'Gillian Larson',
                'Jacquie Berg',
                'Kelly Czarnecki',
                'Ken Hoang',
                'Marcus Lehman',
                'Matty Whitmore',
                'Michelle Chase',
                'Paloma Soto-Castillo',
                'Randy Bailey',
                'Sugar Kiper',
                'Susie Smith']
});

seasonData.set(18, {
    seasonName: "Tocantins",
    seasonWinner: "J.T. Thomas",
    showWinner: false,
    seasonLogo: s18Logo,
    seasonColor: "#5b3d1b",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 2,
    secondChance: "none",
    tier: 1,
    seasonCast: ['Brendan Synnott',
                'Candace Smith',
                'Carolina Eastwood',
                'Coach Wade',
                'Debbie Beebe',
                'Erinn Lobdell',
                'J.T. Thomas',
                'Jerry Sims',
                'Joe Dowdle',
                'Sandy Burgin',
                'Sierra Reed',
                'Spencer Duhm',
                'Stephen Fishbach',
                'Sydney Wheeler',
                'Taj Johnson-George',
                'Tyson Apostol']
});

seasonData.set(19, {
    seasonName: "Samoa",
    seasonWinner: "Natalie White",
    showWinner: false,
    seasonLogo: s19Logo,
    seasonColor: "#cab577",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "none",
    tier: 3,
    seasonCast: ['Ashley Trainer',
                'Ben Browning',
                'Betsy Bolan',
                'Brett Clouser',
                'Dave Ball',
                'Erik Cardona',
                'Jaison Robinson',
                'John Fincher',
                'Kelly Sharbaugh',
                'Laura Morett',
                'Liz Kim',
                'Marisa Calihan',
                'Mick Trimming',
                'Mike Borassi',
                'Monica Padilla',
                'Natalie White',
                'Russell Hantz',
                'Russell Swan',
                'Shambo Waters',
                'Yasmin Giles']
});

seasonData.set(20, {
    seasonName: "Heroes vs Villians", //Heroes vs Villians
    seasonWinner: "Sandra Diaz-Twine",
    showWinner: false,
    seasonLogo: s20Logo,
    seasonColor: "#099567",
    castType: "returnee",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "none",
    tier: 1,
    seasonCast: ['Amanda Kimmel',
                'Candice Cody (Woodcock)',
                'Cirie Fields',
                'Coach Wade',
                'Colby Donaldson',
                'Courtney Yates',
                'Danielle DiLorenzo',
                'J.T. Thomas',
                'James Clement',
                'Jerri Manthey',
                'Parvati Shallow',
                'Randy Bailey',
                'Rob Mariano',
                'Rupert Boneham',
                'Russell Hantz',
                'Sandra Diaz-Twine',
                'Stephenie LaGrossa',
                'Sugar Kiper',
                'Tom Westman',
                'Tyson Apostol']
});

seasonData.set(21, {
    seasonName: "Nicaragua",
    seasonWinner: "Fabio Birza",
    showWinner: false,
    seasonLogo: s21Logo,
    seasonColor: "#612e8b",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "none",
    tier: 4,
    seasonCast: ['Alina Wilson',
                'Benry Henry',
                'Brenda Lowe',
                'Chase Rice',
                'Dan Lembo',
                'Fabio Birza',
                'Holly Hoffman',
                'Jane Bright',
                'Jill Behm',
                'Jimmy Johnson',
                'Jimmy Tarantino',
                'Kelly Bruno',
                'Kelly Shinn',
                'Marty Piombo',
                'NaOnka Mixon',
                'Sash Lenahan',
                'Shannon Elkins',
                'Tyrone Davis',
                'Wendy DeSmidt-Kohlhoff',
                'Yve Rojas']
});

seasonData.set(22, {
    seasonName: "Redemption Island",
    seasonWinner: "Rob Mariano",
    showWinner: false,
    seasonLogo: s22Logo,
    seasonColor: "#854224",
    castType: "mixed",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "redemption",
    tier: 3,
    seasonCast: ['Andrea Boehlke',
                'Ashley Underwood',
                'David Murphy',
                'Francesca Hogi',
                'Grant Mattos',
                'Julie Wolfe',
                'Krista Klumpp',
                'Kristina Kell',
                'Matt Elrod',
                'Mike Chiesl',
                'Natalie Tenerelli',
                'Phillip Sheppard',
                'Ralph Kiser',
                'Rob Mariano',
                'Russell Hantz',
                'Sarita White',
                'Stephanie Valencia',
                'Steve Wright']
});

seasonData.set(23, {
    seasonName: "South Pacific",
    seasonWinner: "Sophie Clarke",
    showWinner: false,
    seasonLogo: s23Logo,
    seasonColor: "#17653e",
    castType: "mixed",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "redemption",
    tier: 3,
    seasonCast: ['Albert Destrade',
                'Brandon Hantz',
                'Christine Shields Markoski',
                'Coach Wade',
                'Dawn Meehan',
                'Edna Ma',
                'Elyse Umemoto',
                'Jim Rice',
                'John Cochran',
                'Keith Tollefson',
                'Mark Caruso',
                'Mikayla Wingle',
                'Ozzy Lusth',
                'Rick Nelson',
                'Semhar Tadesse',
                'Sophie Clarke',
                'Stacey Powell',
                'Whitney Duncan']
});

seasonData.set(24, {
    seasonName: "One World",
    seasonWinner: "Kim Spradlin",
    showWinner: false,
    seasonLogo: s24Logo,
    seasonColor: "#01928c",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "none",
    tier: 2,
    seasonCast: ['Alicia Rosa',
                'Bill Posley',
                'Chelsea Meissner',
                'Christina Cha',
                'Colton Cumbie',
                'Jay Byars',
                'Jonas Otsuji',
                'Kat Edorsson',
                'Kim Spradlin',
                'Kourtney Moon',
                'Leif Manson',
                'Matt Quinlan',
                'Michael Jefferson',
                'Monica Culpepper',
                'Nina Acosta',
                'Sabrina Thompson',
                'Tarzan Smith',
                'Troyzan Robertson']
});

seasonData.set(25, {
    seasonName: "Philippines",
    seasonWinner: "Denise Stapley",
    showWinner: false,
    seasonLogo: s25Logo,
    seasonColor: "#8c1f5a",
    castType: "mixed",
    numTribes: "three",
    finalTribal: 3,
    secondChance: "none",
    tier: 2,
    seasonCast: ['Abi-Maria Gomes',
                'Angie Layton',
                'Artis Silvester',
                'Carter Williams',
                'Dana Lambert',
                'Denise Stapley',
                'Jeff Kent',
                'Jonathan Penner',
                'Katie Hanson',
                'Lisa Whelchel',
                'Malcolm Freberg',
                'Michael Skupin',
                'Pete Yurkowski',
                'RC Saint-Amour',
                'Roxy Morris',
                'Russell Swan',
                'Sarah Dawson',
                'Zane Knight']
});

seasonData.set(26, {
    seasonName: "Caramoan",
    seasonWinner: "John Cochran",
    showWinner: false,
    seasonLogo: s26Logo,
    seasonColor: "#239a92",
    castType: "mixed",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "none",
    tier: 3,
    seasonCast: ['Allie Pohevitz',
                'Andrea Boehlke',
                'Brandon Hantz',
                'Brenda Lowe',
                'Corinne Kaplan',
                'Dawn Meehan',
                'Eddie Fox',
                'Erik Reichenbach',
                'Francesca Hogi',
                'Hope Driskill',
                'John Cochran',
                'Julia Landauer',
                'Laura Alexander',
                'Malcolm Freberg',
                'Matt Bischoff',
                'Michael Snow',
                'Phillip Sheppard',
                'Reynold Toepfer',
                'Shamar Thomas',
                'Sherri Biethman']
});

seasonData.set(27, {
    seasonName: "Blood vs Water",
    seasonWinner: "Tyson Apostol",
    showWinner: false,
    seasonLogo: s27Logo,
    seasonColor: "#c70530",
    castType: "mixed",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "redemption",
    tier: 2,
    seasonCast: ['Aras Baskauskas',
                'Brad Culpepper',
                'Caleb Bankston',
                'Candice Cody (Woodcock)',
                'Ciera Eastin',
                'Colton Cumbie',
                'Gervase Peterson',
                'Hayden Moss',
                'John Cody',
                'Kat Edorsson',
                'Katie Collins',
                'Laura Boneham',
                'Laura Morett',
                'Marissa Peterson',
                'Monica Culpepper',
                'Rachel Foulger',
                'Rupert Boneham',
                'Tina Wesson',
                'Tyson Apostol',
                'Vytas Baskauskas']
});

seasonData.set(28, {
    seasonName: "Cagayan",
    seasonWinner: "Tony Vlachos",
    showWinner: false,
    seasonLogo: s28Logo,
    seasonColor: "#70726f",
    castType: "newbie",
    numTribes: "three",
    finalTribal: 2,
    secondChance: "none",
    tier: 1,
    seasonCast: ['Alexis Maxwell',
                'Brice Johnston',
                'Cliff Robinson',
                'David Samson',
                'Garrett Adelstein',
                "J'Tia Taylor",
                'Jefra Bland',
                'Jeremiah Wood',
                'Kass McQuillen',
                'LJ McKanas',
                'Lindsey Ogle',
                'Morgan McLeod',
                'Sarah Lacina',
                'Spencer Bledsoe',
                'Tasha Fox',
                'Tony Vlachos',
                'Trish Hegarty',
                'Woo Hwang']
});

seasonData.set(29, {
    seasonName: "San Juan del Sur",
    seasonWinner: "Natalie Anderson",
    showWinner: false,
    seasonLogo: s29Logo,
    seasonColor: "#0f978f",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "none",
    tier: 1,
    seasonCast: ['Alec Christy',
                'Baylor Wilson',
                'Dale Wentworth',
                'Drew Christy',
                'Jaclyn Schultz',
                'Jeremy Collins',
                'John Rocker',
                'Jon Misch',
                'Josh Canfield',
                'Julie McGee',
                'Keith Nale',
                'Kelley Wentworth',
                'Missy Payne',
                'Nadiya Anderson',
                'Natalie Anderson',
                'Reed Kelly',
                'Val Collins',
                'Wes Nale']
});

seasonData.set(30, {
    seasonName: "Worlds Apart",
    seasonWinner: "Mike Holloway",
    showWinner: false,
    seasonLogo: s30Logo,
    seasonColor: "#3b4d57",
    castType: "newbie",
    numTribes: "three",
    finalTribal: 3,
    secondChance: "none",
    tier: 4,
    seasonCast: ['Carolyn Rivera',
                'Dan Foley',
                'Hali Ford',
                'Jenn Brown',
                'Joaquin Souberbielle',
                'Joe Anglim',
                'Kelly Remington',
                'Lindsey Cascaddan',
                'Max Dawson',
                'Mike Holloway',
                'Nina Poersch',
                'Rodney Lavoie Jr.',
                'Shirin Oskooi',
                'Sierra Dawn Thomas',
                'So Kim',
                'Tyler Fredrickson',
                'Vince Sly',
                'Will Sims II']
});

seasonData.set(31, {
    seasonName: "Cambodia",
    seasonWinner: "Jeremy Collins",
    showWinner: false,
    seasonLogo: s31Logo,
    seasonColor: "#fa2ac3",
    castType: "returnee",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "none",
    tier: 1,
    seasonCast: ['Abi-Maria Gomes', 
                'Andrew Savage',
                'Ciera Eastin',
                'Jeff Varner',
                'Jeremy Collins',
                'Joe Anglim',
                'Kass McQuillen',
                'Keith Nale',
                'Kelley Wentworth',
                'Kelly Wiglesworth',
                'Kimmi Kappenberg',
                'Monica Padilla',
                'Peih-Gee Law',
                'Shirin Oskooi',
                'Spencer Bledsoe',
                'Stephen Fishbach',
                'Tasha Fox',
                'Terry Deitz',
                'Vytas Baskauskas',
                'Woo Hwang']
});

seasonData.set(32, {
    seasonName: "Kaoh Rong",
    seasonWinner: "Michele Fitzgerald",
    showWinner: false,
    seasonLogo: s32Logo,
    seasonColor: "#d2202d",
    castType: "newbie",
    numTribes: "three",
    finalTribal: 3,
    secondChance: "none",
    tier: 3,
    seasonCast: ['Alecia Holden',
                'Anna Khait',
                'Aubry Bracco',
                'Caleb Reynolds',
                'Cydney Gillon',
                'Darnell Hamilton',
                'Debbie Wanner',
                'Jennifer Lanzetti',
                'Joe del Campo',
                'Julia Sokolowski',
                'Kyle Jason',
                'Liz Markham',
                'Michele Fitzgerald',
                'Neal Gottlieb',
                'Nick Maiorano',
                'Peter Baggenstos',
                'Scot Pollard',
                'Tai Trang']
});

seasonData.set(33, {
    seasonName: "Millennials vs GenX",
    seasonWinner: "Adam Klein",
    showWinner: false,
    seasonLogo: s33Logo,
    seasonColor: "#865d31",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "none",
    tier: 2,
    seasonCast: ['Adam Klein',
                'Bret LaBelle',
                'CeCe Taylor',
                'Chris Hammons',
                'David Wright',
                'Figgy Figueroa',
                'Hannah Shapiro',
                'Jay Starrett',
                'Jessica Lewis',
                'Ken McNickle',
                'Lucy Huang',
                'Mari Takahashi',
                'Michaela Bradshaw',
                'Michelle Schubert',
                'Paul Wachter',
                'Rachel Ako',
                'Sunday Burquest',
                'Taylor Stocker',
                'Will Wahl',
                'Zeke Smith']
});

seasonData.set(34, {
    seasonName: "Game Changers",
    seasonWinner: "Sarah Lacina",
    showWinner: false,
    seasonLogo: s34Logo,
    seasonColor: "#19458c",
    castType: "returnee",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "none",
    tier: 3,
    seasonCast: ['Andrea Boehlke',
                'Aubry Bracco',
                'Brad Culpepper',
                'Caleb Reynolds',
                'Ciera Eastin',
                'Cirie Fields',
                'Debbie Wanner',
                'Hali Ford',
                'J.T. Thomas',
                'Jeff Varner',
                'Malcolm Freberg',
                'Michaela Bradshaw',
                'Ozzy Lusth',
                'Sandra Diaz-Twine',
                'Sarah Lacina',
                'Sierra Dawn Thomas',
                'Tai Trang',
                'Tony Vlachos',
                'Troyzan Robertson',
                'Zeke Smith']
});

seasonData.set(35, {
    seasonName: "Heroes, Healers, Hustlers",
    seasonWinner: "Ben Driebergen",
    showWinner: false,
    seasonLogo: s35Logo,
    seasonColor: "#ff9e19",
    castType: "newbie",
    numTribes: "three",
    finalTribal: 3,
    secondChance: "none",
    tier: 3,
    seasonCast: ['Alan Ball',
                'Ali Elliott',
                'Ashley Nolan',
                'Ben Driebergen',
                'Chrissy Hofbeck',
                'Cole Medders',
                'Desi Williams',
                'Devon Pinto',
                'JP Hilsabeck',
                'Jessica Johnston',
                'Joe Mena',
                'Katrina Radke',
                'Lauren Rimmer',
                'Mike Zahalsky',
                'Patrick Bolton',
                'Roark Luskin',
                'Ryan Ulrich',
                'Simone Nguyen']
});

seasonData.set(36, {
    seasonName: "Ghost Island",
    seasonWinner: "Wendell Holland",
    showWinner: false,
    seasonLogo: s36Logo,
    seasonColor: "#216093",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "none",
    tier: 2,
    seasonCast: ['Angela Perkins',
                'Bradley Kleihege',
                'Brendan Shapiro',
                'Chelsea Townsend',
                'Chris Noble',
                'Desiree Afuye',
                'Domenick Abbate',
                'Donathan Hurley',
                'Jacob Derwin',
                'James Lim',
                'Jenna Bowman',
                'Kellyn Bechtold',
                'Laurel Johnson',
                'Libby Vincek',
                'Michael Yerger',
                'Morgan Ricke',
                'Sebastian Noel',
                'Stephanie Gonzalez',
                'Stephanie Johnson',
                'Wendell Holland']
});

seasonData.set(37, {
    seasonName: "David vs Goliath",
    seasonWinner: "Nick Wilson",
    showWinner: false,
    seasonLogo: s37Logo,
    seasonColor: "#a1d75c",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "none",
    tier: 1,
    seasonCast: ['Alec Merlino',
                'Alison Raybould',
                'Angelina Keeley',
                'Bi Nguyen',
                'Carl Boudreaux',
                'Christian Hubicki',
                'Dan Rengering',
                'Davie Rickenbacker',
                'Elizabeth Olson',
                'Gabby Pascuzzi',
                'Jeremy Crawford',
                'Jessica Peet',
                'John Hennigan',
                'Kara Kay',
                'Lyrsa Torres',
                'Mike White',
                'Natalia Azoqa',
                'Natalie Cole',
                'Nick Wilson',
                'Pat Cusack']
});

seasonData.set(38, {
    seasonName: "Edge of Extinction",
    seasonWinner: "Chris Underwood",
    showWinner: false,
    seasonLogo: s38Logo,
    seasonColor: "#563383",
    castType: "mixed",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "edge",
    tier: 4,
    seasonCast: ['Aubry Bracco',
                'Aurora McCreary',
                'Chris Underwood',
                'David Wright',
                'Eric Hafemann',
                'Gavin Whitson',
                'Joe Anglim',
                'Julia Carter',
                'Julie Rosenberg',
                'Keith Sowell',
                'Kelley Wentworth',
                "Lauren O'Connell",
                'Reem Daly',
                'Rick Devens',
                'Ron Clark',
                'Victoria Baamonde',
                'Wardog DaSilva',
                'Wendy Diaz']
});

seasonData.set(39, {
    seasonName: "Island of the Idols",
    seasonWinner: "Tommy Sheehan",
    showWinner: false,
    seasonLogo: s39Logo,
    seasonColor: "#32bad3",
    castType: "newbie",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "none",
    tier: 4,
    seasonCast: ['Aaron Meredith',
                'Chelsea Walker',
                'Dan Spilo',
                'Dean Kowalski',
                'Elaine Stott',
                'Elizabeth Beisel',
                'Jack Nichting',
                'Jamal Shipman',
                'Janet Carbin',
                'Jason Linden',
                'Karishma Patel',
                'Kellee Kim',
                'Lauren Beck',
                'Missy Byrd',
                'Molly Byman',
                'Noura Salman',
                'Ronnie Bardah',
                'Tom Laidlaw',
                'Tommy Sheehan',
                'Vince Moua']
});

seasonData.set(40, {
    seasonName: "Winners at War",
    seasonWinner: "Tony Vlachos",
    showWinner: false,
    seasonLogo: s40Logo,
    seasonColor: "#005b90",
    castType: "returnee",
    numTribes: "two",
    finalTribal: 3,
    secondChance: "edge",
    tier: 1,
    seasonCast: ['Adam Klein',
                "Amber Mariano (Brkich)",
                'Ben Driebergen',
                'Danni Boatwright',
                'Denise Stapley',
                'Ethan Zohn',
                'Jeremy Collins',
                'Kim Spradlin',
                'Michele Fitzgerald',
                'Natalie Anderson',
                'Nick Wilson',
                'Parvati Shallow',
                'Rob Mariano',
                'Sandra Diaz-Twine',
                'Sarah Lacina',
                'Sophie Clarke',
                'Tony Vlachos',
                'Tyson Apostol',
                'Wendell Holland',
                'Yul Kwon']
});

seasonData.set(41, {
    seasonName: "41",
    seasonWinner: "Erika Casupanan",
    showWinner: false,
    seasonLogo: s41Logo,
    seasonColor: "#adc8e5",
    castType: "newbie",
    numTribes: "three",
    finalTribal: 3,
    secondChance: "none",
    tier: 2,
    seasonCast: ['Brad Reese',
                'Danny McCray',
                'David Voce',
                'Deshawn Radden',
                'Eric Abraham',
                'Erika Casupanan',
                'Evvie Jagoda',
                'Genie Chen',
                'Heather Aldret',
                'JD Robinson',
                'Liana Wallace',
                'Naseer Muttalif',
                'Ricard Foyé',
                'Sara Wilson',
                'Shan Smith',
                'Sydney Segal',
                'Tiffany Seely',
                'Xander Hastings']
});


export const numSeasons = seasonData.size;
export default seasonData;